# Generated by Django 4.2.20 on 2025-04-11 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_location_event_address_event_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_registered_events', models.BooleanField(default=True)),
                ('personalized_recommendations', models.BooleanField(default=True)),
                ('platform_news', models.BooleanField(default=True)),
                ('trending_events_in_city', models.BooleanField(default=True)),
                ('interest_based_recommendations', models.BooleanField(default=True)),
                ('birthday_greetings', models.BooleanField(default=True)),
                ('event_changes', models.BooleanField(default=True)),
                ('new_messages', models.BooleanField(default=True)),
                ('upcoming_event_reminders', models.BooleanField(default=True)),
                ('someone_interested_in_event', models.BooleanField(default=True)),
                ('event_time_or_location_changes', models.BooleanField(default=True)),
                ('exclusive_promotions', models.BooleanField(default=True)),
                ('private_account', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
