# Generated by Django 4.2.20 on 2025-04-12 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('remind_registered_events', 'Reminder for Registered Events'), ('personalized_recommendations', 'Personalized Recommendations'), ('platform_news', 'Platform News and Updates'), ('trending_events_in_city', 'Trending Events in Your City'), ('interest_based_recommendations', 'Recommendations Based on Your Interests'), ('birthday_greetings', 'Birthday and Holiday Greetings'), ('event_changes', 'Notifications about Event Changes'), ('new_messages', 'New Messages from Organizers or Participants'), ('upcoming_event_reminders', 'Reminders for Upcoming Events'), ('someone_interested_in_event', 'Someone is Interested in Your Event'), ('event_time_or_location_changes', 'Event Date, Time, or Location Changes'), ('exclusive_promotions', 'Exclusive Deals and Promotions')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
