# Generated by Django 4.2.20 on 2025-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_eventphoto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
