# Generated by Django 4.2.20 on 2025-04-17 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_eventphoto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('remind_registered_events', 'Reminder for Registered Events'), ('personalized_recommendations', 'Personalized Recommendations'), ('platform_news', 'Platform News and Updates'), ('trending_events_in_city', 'Trending Events in Your City'), ('interest_based_recommendations', 'Recommendations Based on Your Interests'), ('birthday_greetings', 'Birthday and Holiday Greetings'), ('event_changes', 'Notifications about Event Changes'), ('new_messages', 'New Messages from Organizers or Participants'), ('upcoming_event_reminders', 'Reminders for Upcoming Events'), ('someone_interested_in_event', 'Someone is Interested in Your Event'), ('event_time_or_location_changes', 'Event Date, Time, or Location Changes'), ('exclusive_promotions', 'Exclusive Deals and Promotions'), ('friend_request', 'Friend Request Received'), ('friend_request_accepted', 'Friend Request Accepted')], max_length=50),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
