# Generated by Django 5.1.7 on 2025-04-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_eventphoto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
