# Generated by Django 4.2.20 on 2025-04-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_notification_type_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
