# Generated by Django 4.2.20 on 2025-04-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
