# Generated by Django 4.2.20 on 2025-05-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_event_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memorymention',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='memorymention',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userfriend'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('event_joined', 'Someone joined your event'), ('friend_joined_event', 'Your friend joined an event'), ('friend_recommended_event', 'Your friend recommended an event'), ('friend_created_event', 'Your friend created an event'), ('event_announcement', 'Announcement for Event Participants'), ('event_reminder_1d', 'Event Reminder: 1 Day Before'), ('event_reminder_2h', 'Event Reminder: 2 Hours Before'), ('event_deleted', 'Event Cancelled'), ('friend_request', 'New Friend Request'), ('friend_request_accepted', 'Friend Request Accepted')], max_length=50),
        ),
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='MemoryMention',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
