# Generated by Django 4.2.20 on 2025-05-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_eventphoto_event_favoriteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='friend_request',
            field=models.BooleanField(default=True),
        ),
    ]
