# Generated by Django 5.1.7 on 2025-06-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_location_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='birthday_greetings',
            new_name='event_announcement',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='event_changes',
            new_name='event_deleted',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='event_time_or_location_changes',
            new_name='event_joined',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='exclusive_promotions',
            new_name='event_reminder_1d',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='interest_based_recommendations',
            new_name='event_reminder_2h',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='new_messages',
            new_name='friend_created_event',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='personalized_recommendations',
            new_name='friend_joined_event',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='platform_news',
            new_name='friend_recommended_event',
        ),
        migrations.RenameField(
            model_name='usersettings',
            old_name='remind_registered_events',
            new_name='friend_request_accepted',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='someone_interested_in_event',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='trending_events_in_city',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='upcoming_event_reminders',
        ),
    ]
