# Generated by Django 5.1.7 on 2025-06-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_birthday_greetings_usersettings_event_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_avatars/'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='users.event'),
        ),
    ]
